# Puerto donde correrá Eureka Server.
server.port=8761

# Nombre del servidor de registro.
spring.application.name=EUREKA-SERVER

# Eureka no se registra a sí mismo.
eureka.client.register-with-eureka=false

# Eureka no consulta otro registro.
eureka.client.fetch-registry=false

# Permite que los servicios se registren sin esperar una sincronización inicial.
eureka.server.wait-time-in-ms-when-sync-empty=0

# Expone endpoints básicos de monitoreo.
management.endpoints.web.exposure.include=health,info
