server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/v1/usuarios/**
            # Se pueden agregar filtros específicos para este microservicio si es necesario
            #como filtros de autenticación, autorización, etc.
            #filters:
            #  - name: AuthenticationFilter
            #   roles: [ADMIN, USER] D
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/api/v1/productos/**
        - id: ms-pedidos
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/v1/pedidos/**
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/v1/pagos/**
        - id: ms-envios
          uri: lb://ms-envios
          predicates:
            - Path=/api/v1/envios/**
        - id: ms-inventario
          uri: lb://ms-inventario
          predicates:
            - Path=/api/v1/inventario/**
        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/v1/notificaciones/**
        - id: ms-resenas
          uri: lb://ms-resenas
          predicates:
            - Path=/api/v1/resenas/**
        - id: ms-cupones
          uri: lb://ms-cupones
          predicates:
            - Path=/api/v1/cupones/**

# ==========================================
# CONFIGURACIÓN DE SWAGGER CENTRALIZADO
# ==========================================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    configUrl: /v3/api-docs/swagger-config
    urls:
      - name: 1. Autenticación (ms-auth)
        url: /api/v1/auth/v3/api-docs
      - name: 2. Usuarios (ms-usuarios)
        url: /api/v1/usuarios/v3/api-docs
      - name: 3. Productos (ms-productos)
        url: /api/v1/productos/v3/api-docs
      - name: 4. Pedidos (ms-pedidos)
        url: /api/v1/pedidos/v3/api-docs
      - name: 5. Pagos (ms-pagos)
        url: /api/v1/pagos/v3/api-docs
      - name: 6. Envíos (ms-envios)
        url: /api/v1/envios/v3/api-docs
      - name: 7. Inventario (ms-inventario)
        url: /api/v1/inventario/v3/api-docs
      - name: 8. Notificaciones (ms-notificaciones)
        url: /api/v1/notificaciones/v3/api-docs
      - name: 9. Reseñas (ms-resenas)
        url: /api/v1/resenas/v3/api-docs
      - name: 10. Cupones (ms-cupones)
        url: /api/v1/cupones/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: foodexpresssupersecretkey2026foodexpresssupersecretkey