name: foodexpress

services:
  mysql:
    image: mysql:8.4
    container_name: foodexpress-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: db_usuario
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -psystem --silent"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - foodexpress-net

  eureka-server:
    build: ./eureka-server
    container_name: foodexpress-eureka
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: "8761"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    ports:
      - "8761:8761"
    networks:
      - foodexpress-net

  api-gateway:
    build: ./api-gateway
    container_name: foodexpress-gateway
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: clave-super-secreta-para-clase-123456
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - foodexpress-net

  ms-auth:
    build: ./ms-auth
    container_name: foodexpress-ms-auth
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_usuario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: clave-super-secreta-para-clase-123456
      JWT_EXPIRATION: "3600000"
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-usuarios:
    build: ./ms-usuarios
    container_name: foodexpress-ms-usuarios
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_usuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-productos:
    build: ./ms-productos
    container_name: foodexpress-ms-productos
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_productos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-pedidos:
    build: ./ms-pedidos
    container_name: foodexpress-ms-pedidos
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_pedidos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-pagos:
    build: ./ms-pagos
    container_name: foodexpress-ms-pagos
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_pagos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-envios:
    build: ./ms-envios
    container_name: foodexpress-ms-envios
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_envios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-inventario:
    build: ./ms-inventario
    container_name: foodexpress-ms-inventario
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_inventario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-notificaciones:
    build: ./ms-notificaciones
    container_name: foodexpress-ms-notificaciones
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_notificaciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-resenas:
    build: ./ms-resenas
    container_name: foodexpress-ms-resenas
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_resenas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

  ms-cupones:
    build: ./ms-cupones
    container_name: foodexpress-ms-cupones
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_cupones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - foodexpress-net

volumes:
  mysql_data:

networks:
  foodexpress-net:
    driver: bridge
